### ISSUE TITLE
Prefer forge-std's test

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#205]
I think we should prefer forge-std's test setup instead of just DSTest for examples/guides. We will probably also need to document it somehow - maybe even replace the DSTest reference?

See https://github.com/foundry-rs/forge-std/pull/36

**Comment by ZeroEkkusu** [comment]
Forge Std needs better docs anyway; we should dedicate a section in References to it.

IMO, the book should set an example on best/recommended practices.
Prefer `Test` over `DSTest`, in this case.

Idea on how to structure the Forge Std reference: leave ds-test Reference and Cheatcodes Reference as they are (because they exist separate of the Forge Std lib), then reference them in Forge Std Reference - which would be similar to Cheatcodes Reference. Will think about this.
