### ISSUE TITLE
Document `console2.sol`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/book#222]
Details in https://github.com/foundry-rs/foundry/pull/1367

Can probably pull the text to use from the forge-std README https://github.com/foundry-rs/forge-std/pull/44

**Comment by onbjerg** [comment]
@ZeroEkkusu Could you add this to #207? I'd just mention the differences:

**console.sol**

- Shows up as logs in both Hardhat and Forge
- Will not show up in traces

**console2.sol**

- Only works for Forge
- Shows up in traces in Forge

And then maybe briefly that it is due to a bug in the original console.sol

**Comment by mds1** [comment]
`console.sol` will show up in traces, but it will be undecoded if you use a log with `int256` or `uint256`

**Comment by onbjerg** [comment]
Ah right, good distinction!
