### ISSUE TITLE
Document what is the minimum supported Solidity version

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/book#455]
It would be helpful to add a mention about the minimum supported Solidity version in the [How do I use a specific Solidity compiler?](https://book.getfoundry.sh/faq?highlight=solidity#how-do-i-use-a-specific-solidity-compiler) section of the book.

**Comment by onbjerg** [comment]
I don't think anyone knows what the minimum supported is. I've seen people use 0.5.0 and above, and I don't know of any projects that use below 0.5.0?

**Comment by paulrberg** [comment]
There must be someone that knows this 😅

AFAIK, Foundry uses [svm-rs](https://github.com/roynalnaruto/svm-rs) to manage Solidity compilers. Perhaps @roynalnaruto could help us here?

**Comment by onbjerg** [comment]
svm-rs supports any Solidity compiler version that is downloadable. The minimum version is a complex question since different parts of Forge probably have different supported versions. For example, the formatter supports whatever solang-parser supports, `forge test` supports any version that `forge build` supports (since we just need an ABI), it's not entirely clear what `forge build` supports since it depends on the compiler input/output description, and `forge coverage` most definitely will not support anything under 0.5.0 in most cases

**Comment by paulrberg** [comment]
> The minimum version is a complex question since different parts of Forge probably have different supported versions

Oh, I didn't know this. Sorry, and thanks for explaining.

I will then close this issue.

FWIW: the reason I was asking was that I have been working on a new GitHub Action for Foundry, which I intended to do something different based upon the Solidity versions passed by the user. Obviously I needed to use a min and a max for that.

But at any rate, I have abandoned that idea in favor of making a PR in the `foundry` directly.
